pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - status-success=build (ubuntu-latest, 2.6.x)
      - status-success=build (macos-latest, 2.6.x)
      - status-success=build (windows-latest, 2.6.x)
    actions:
      merge:
        method: squash
